// Sample performers used ONLY until the Google Sheet is published. Coordinates
// are real spots around Portsmouth, NH so the map looks alive while you design.
// The moment the live sheet returns rows, these are ignored automatically.
//
// These rows match the exact column shape the Google Sheet should use, so the
// popup/marker code is identical for sample and live data.
export const SAMPLE_BANDS = [
  {
    name: 'The Clamdiggers',
    address: '211 Richards Ave, Portsmouth, NH',
    lat: '43.0699',
    lng: '-70.7558',
    zone: '1',
    time_start: '12:00 PM',
    time_end: '1:00 PM',
    genre: 'Folk',
    description: 'Three-part harmonies and a washtub bass on the South End.',
    image: 'https://picsum.photos/seed/clamdiggers/480/280',
    link: 'https://bandcamp.com',
  },
  {
    name: 'Saltbox Revival',
    address: '88 South St, Portsmouth, NH',
    lat: '43.0712',
    lng: '-70.7589',
    zone: '1',
    time_start: '1:00 PM',
    time_end: '2:00 PM',
    genre: 'Americana',
    description: 'Dusty Americana with pedal steel and close harmony.',
    image: 'https://picsum.photos/seed/saltbox/480/280',
    link: '',
  },
  {
    name: 'Wibird Street Stompers',
    address: '75 Wibird St, Portsmouth, NH',
    lat: '43.0651',
    lng: '-70.7601',
    zone: '2',
    time_start: '2:00 PM',
    time_end: '3:00 PM',
    genre: 'Funk / Soul',
    description: 'Eight-piece funk outfit that turns a porch into a dance floor.',
    image: 'https://picsum.photos/seed/stompers/480/280',
    link: 'https://soundcloud.com',
  },
  {
    name: 'The Gundalows',
    address: '142 Lincoln Ave, Portsmouth, NH',
    lat: '43.0760',
    lng: '-70.7610',
    zone: '2',
    time_start: '3:00 PM',
    time_end: '4:00 PM',
    genre: 'Indie Rock',
    description: 'Jangly guitars and big choruses from the West End.',
    image: 'https://picsum.photos/seed/gundalows/480/280',
    link: '',
  },
  {
    name: 'Goodwin Park Brass',
    address: 'Goodwin Park, Islington St, Portsmouth, NH',
    lat: '43.0735',
    lng: '-70.7665',
    zone: '3',
    time_start: '4:00 PM',
    time_end: '5:00 PM',
    genre: 'Brass / Jazz',
    description: 'New Orleans–style brass band marching the park paths.',
    image: 'https://picsum.photos/seed/brass/480/280',
    link: 'https://youtube.com',
  },
  {
    name: 'Little Harbor Trio',
    address: '300 Marcy St, Portsmouth, NH',
    lat: '43.0742',
    lng: '-70.7536',
    zone: '3',
    time_start: '5:00 PM',
    time_end: '6:00 PM',
    genre: 'Jazz',
    description: 'Standards and bossa by the water near Prescott Park.',
    image: 'https://picsum.photos/seed/littleharbor/480/280',
    link: '',
  },
];
